//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_MemberActivity
    {
        public long Id { get; set; }
        public Nullable<long> LogId { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string MemberEmail { get; set; }
        public string MemberName { get; set; }
        public string VisitedIP { get; set; }
        public string SessionID { get; set; }
        public string VisitedRawURL { get; set; }
        public string ReferredURL { get; set; }
        public Nullable<System.DateTime> LoggedTime { get; set; }
    }
}
