//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_MemberSession
    {
        public long Id { get; set; }
        public long LogId { get; set; }
        public long MemberId { get; set; }
        public string VisitedIP { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> SessionIn { get; set; }
        public Nullable<System.DateTime> LogIn { get; set; }
        public Nullable<System.DateTime> LogOut { get; set; }
        public Nullable<System.DateTime> SessionOut { get; set; }
        public string ReferredURL { get; set; }
        public string VisitedURL { get; set; }
        public string VisitedCity { get; set; }
        public string VisitedCountry { get; set; }
    }
}
