//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_MemberMaster
    {
        public long Id { get; set; }
        public Nullable<long> LogId { get; set; }
        public string Email_Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string Status_Email { get; set; }
        public string Status_Member { get; set; }
        public string MemberClass { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string RegisteredIP { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> ActivationCodeExpired { get; set; }
        public Nullable<System.DateTime> LoggedDate { get; set; }
    }
}
