//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyFavorite
    {
        public long Id { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<long> ProfileID { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIP { get; set; }
    
        public virtual MemberMaster MemberMaster { get; set; }
        public virtual Profile_Master Profile_Master { get; set; }
    }
}
