//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Master
    {
        public Profile_Master()
        {
            this.MyFavorites = new HashSet<MyFavorite>();
            this.Profile_Links = new HashSet<Profile_Links>();
            this.Profile_Subjects = new HashSet<Profile_Subjects>();
            this.Reviews = new HashSet<Review>();
        }
    
        public long Id { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string OnlineTutoring { get; set; }
        public string OnsiteTutoring { get; set; }
        public Nullable<int> Travel { get; set; }
        public string TravelUnit { get; set; }
        public string TutoringExperience { get; set; }
        public string TutoringGrade { get; set; }
        public Nullable<decimal> HourlyFee { get; set; }
        public string CurrencyUnit { get; set; }
        public string CancellationPolicy { get; set; }
        public Nullable<double> OverallRating { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIP { get; set; }
    
        public virtual MemberMaster MemberMaster { get; set; }
        public virtual ICollection<MyFavorite> MyFavorites { get; set; }
        public virtual ICollection<Profile_Links> Profile_Links { get; set; }
        public virtual ICollection<Profile_Subjects> Profile_Subjects { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
