//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long Id { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public Nullable<long> ReviewerId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewTitle { get; set; }
        public string Subject { get; set; }
        public string Subject_Detail { get; set; }
        public string SessionLocation { get; set; }
        public string SessionDate { get; set; }
        public string SessionHours { get; set; }
        public string ReviewSummary { get; set; }
        public string Description_SubjectKnowledge { get; set; }
        public string Description_Helpfullness { get; set; }
        public string Description_Passion { get; set; }
        public Nullable<int> Score_SubjectKnowledge { get; set; }
        public Nullable<int> Score_Helpfullness { get; set; }
        public Nullable<int> Score_Passion { get; set; }
        public Nullable<int> Score_Overall { get; set; }
        public string Status_Screen { get; set; }
        public string Status_Show { get; set; }
        public Nullable<long> Status_ReviewId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedIP { get; set; }
        public Nullable<int> Communication { get; set; }
    
        public virtual MemberMaster MemberMaster { get; set; }
        public virtual Profile_Master Profile_Master { get; set; }
        public virtual Status_Reviews Status_Reviews { get; set; }
    }
}
