//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Subjects
    {
        public Status_Subjects()
        {
            this.Profile_Subjects = new HashSet<Profile_Subjects>();
        }
    
        public long Id { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Profile_Subjects> Profile_Subjects { get; set; }
    }
}
