//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextContent
    {
        public long Id { get; set; }
        public string PageID { get; set; }
        public Nullable<long> LanguageId { get; set; }
        public string TitleHTML { get; set; }
        public string BodyHTML { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIP { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Status_TextContents Status_TextContents { get; set; }
    }
}
