//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMaster
    {
        public MemberMaster()
        {
            this.MyFavorites = new HashSet<MyFavorite>();
            this.MyMessages = new HashSet<MyMessage>();
            this.MyMessages1 = new HashSet<MyMessage>();
            this.MyMessages2 = new HashSet<MyMessage>();
            this.Profile_EduBackground = new HashSet<Profile_EduBackground>();
            this.Profile_Master = new HashSet<Profile_Master>();
            this.Reviews = new HashSet<Review>();
        }
    
        public long Id { get; set; }
        public string Email_Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Cover_File { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string Status_Email { get; set; }
        public Nullable<long> Status_MemberId { get; set; }
        public string MemberClass { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string RegisteredIP { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> ActivationCodeExpired { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public Nullable<long> MemberRoleId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual MemberRole MemberRole { get; set; }
        public virtual State State { get; set; }
        public virtual Status_Members Status_Members { get; set; }
        public virtual ICollection<MyFavorite> MyFavorites { get; set; }
        public virtual ICollection<MyMessage> MyMessages { get; set; }
        public virtual ICollection<MyMessage> MyMessages1 { get; set; }
        public virtual ICollection<MyMessage> MyMessages2 { get; set; }
        public virtual ICollection<Profile_EduBackground> Profile_EduBackground { get; set; }
        public virtual ICollection<Profile_Master> Profile_Master { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
