//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyMessage
    {
        public long Id { get; set; }
        public Nullable<long> ToId { get; set; }
        public Nullable<long> CcId { get; set; }
        public Nullable<long> SenderId { get; set; }
        public string Subject { get; set; }
        public string BodyText { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public Nullable<long> StatusReadId { get; set; }
        public Nullable<long> StatusDeleteId { get; set; }
        public Nullable<long> StatusLabelId { get; set; }
    
        public virtual MemberMaster MemberMaster { get; set; }
        public virtual MemberMaster MemberMaster1 { get; set; }
        public virtual MemberMaster MemberMaster2 { get; set; }
        public virtual Status_Messages Status_Messages { get; set; }
        public virtual Status_Messages Status_Messages1 { get; set; }
        public virtual Status_Messages Status_Messages2 { get; set; }
    }
}
