//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Members
    {
        public Status_Members()
        {
            this.MemberMasters = new HashSet<MemberMaster>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
    
        public virtual ICollection<MemberMaster> MemberMasters { get; set; }
    }
}
