//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFax.Web.CORE.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFaxEntities : DbContext
    {
        public TFaxEntities()
            : base("name=TFaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City> Cities { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<HTTPTraceListener> HTTPTraceListeners { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Log_MemberActivity> Log_MemberActivity { get; set; }
        public DbSet<Log_MemberMaster> Log_MemberMaster { get; set; }
        public DbSet<Log_MemberSession> Log_MemberSession { get; set; }
        public DbSet<MemberMaster> MemberMasters { get; set; }
        public DbSet<MemberRole> MemberRoles { get; set; }
        public DbSet<MyFavorite> MyFavorites { get; set; }
        public DbSet<MyMessage> MyMessages { get; set; }
        public DbSet<Profile_EduBackground> Profile_EduBackground { get; set; }
        public DbSet<Profile_Links> Profile_Links { get; set; }
        public DbSet<Profile_Master> Profile_Master { get; set; }
        public DbSet<Profile_Subjects> Profile_Subjects { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Status_EduBackground> Status_EduBackground { get; set; }
        public DbSet<Status_Links> Status_Links { get; set; }
        public DbSet<Status_Members> Status_Members { get; set; }
        public DbSet<Status_Messages> Status_Messages { get; set; }
        public DbSet<Status_Reviews> Status_Reviews { get; set; }
        public DbSet<Status_Subjects> Status_Subjects { get; set; }
        public DbSet<Status_TextContents> Status_TextContents { get; set; }
        public DbSet<TextContent> TextContents { get; set; }
    }
}
